// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGsuns66FpM8GQw6YoxDGjcy5nG1RfN2g',
    appId: '1:1014233301918:web:fdb7f71b888d212633cc8f',
    messagingSenderId: '1014233301918',
    projectId: 'etica-proyecto-f872b',
    authDomain: 'etica-proyecto-f872b.firebaseapp.com',
    storageBucket: 'etica-proyecto-f872b.firebasestorage.app',
    measurementId: 'G-V3192D82LX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT_E9jnDKb9TONcbz4-D_xgYSHC1vFIFk',
    appId: '1:1014233301918:android:dd7e4311cb00cfd033cc8f',
    messagingSenderId: '1014233301918',
    projectId: 'etica-proyecto-f872b',
    storageBucket: 'etica-proyecto-f872b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFh3Nyt36DhIMG8tRf-kwUVRa7buAVxNM',
    appId: '1:1014233301918:ios:ad2ef648fe8837b833cc8f',
    messagingSenderId: '1014233301918',
    projectId: 'etica-proyecto-f872b',
    storageBucket: 'etica-proyecto-f872b.firebasestorage.app',
    iosBundleId: 'com.example.anmiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFh3Nyt36DhIMG8tRf-kwUVRa7buAVxNM',
    appId: '1:1014233301918:ios:ad2ef648fe8837b833cc8f',
    messagingSenderId: '1014233301918',
    projectId: 'etica-proyecto-f872b',
    storageBucket: 'etica-proyecto-f872b.firebasestorage.app',
    iosBundleId: 'com.example.anmiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGsuns66FpM8GQw6YoxDGjcy5nG1RfN2g',
    appId: '1:1014233301918:web:9d979180baad713033cc8f',
    messagingSenderId: '1014233301918',
    projectId: 'etica-proyecto-f872b',
    authDomain: 'etica-proyecto-f872b.firebaseapp.com',
    storageBucket: 'etica-proyecto-f872b.firebasestorage.app',
    measurementId: 'G-K7CD5G99SK',
  );
}
